-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE AS s
LEFT JOIN USER_INFO AS u
ON s.USER_ID = u.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
