-- 코드를 입력하세요

SELECT 
    CAR_ID,
    c.CAR_TYPE,
    ROUND(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p
ON c.CAR_TYPE = p.CAR_TYPE
WHERE (CAR_ID NOT IN (SELECT 
                        CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'))
    AND (c.CAR_TYPE IN ("세단", "SUV"))
    AND p.DURATION_TYPE = "30일 이상"
    AND ROUND(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
