-- 코드를 입력하세요
SELECT
    a.FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM REST_INFO AS a
RIGHT JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS M
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS b
ON a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.M
ORDER BY FOOD_TYPE DESC