-- 코드를 입력하세요
SELECT
    *
FROM (
    SELECT 
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE
    UNION
    SELECT 
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM ONLINE_SALE
) AS a
WHERE MONTH(SALES_DATE) = '3'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
