-- 코드를 작성해주세요
SELECT  ITEM_ID, ITEM_NAME, RARITY
FROM
(
    SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY, T.PARENT_ITEM_ID
    FROM ITEM_INFO AS I
    LEFT JOIN ITEM_TREE AS T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
) AS A
WHERE PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC