-- 코드를 입력하세요
SELECT 
    MONTH(o.START_DATE) AS MONTH,
    o.CAR_ID,
    COUNT(o.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS o
INNER JOIN (
        SELECT
            CAR_ID,
            COUNT(CAR_ID) AS cnt
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN DATE("2022-08-01") AND DATE("2022-10-31")
        GROUP BY CAR_ID
        HAVING cnt > 4
) AS f
ON f.CAR_ID = o.CAR_ID
WHERE START_DATE BETWEEN DATE("2022-08-01") AND DATE("2022-10-31")
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC
