-- 코드를 입력하세요
SELECT
    CAR_ID,
    IF (SUM(BOOL) = 0, '대여 가능', '대여중') AS AVAILABILITY
FROM (
    SELECT
        CAR_ID, 
        IF (DATE("2022-10-16") BETWEEN START_DATE AND END_DATE, 1, 0) AS BOOL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS h
GROUP BY CAR_ID
ORDER BY CAR_ID DESC    