-- 코드를 입력하세요
SELECT 
    TITLE, 
    R.BOARD_ID, 
    REPLY_ID, 
    R.WRITER_ID, 
    R.CONTENTS, 
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_REPLY AS R
    ON B.BOARD_ID = R.BOARD_ID
WHERE MONTH(B.CREATED_DATE) = 10
ORDER BY CREATED_DATE, TITLE;