-- 코드를 입력하세요
SELECT
    p.PRODUCT_ID,
    PRODUCT_NAME,
    PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS p
INNER JOIN (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE MONTH(PRODUCE_DATE) = '5' AND YEAR(PRODUCE_DATE) = '2022'
    GROUP BY PRODUCT_ID
) AS o
ON p.PRODUCT_ID = o.PRODUCT_ID

ORDER BY TOTAL_SALES DESC, PRODUCT_ID