-- 코드를 작성해주세요

SELECT 
    SCORE,
    e.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_EMPLOYEES AS e 
INNER JOIN
(SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE 
 WHERE YEAR=2022 GROUP BY EMP_NO ORDER BY SCORE DESC LIMIT 1)
AS g ON e.EMP_NO = g.EMP_NO