-- 코드를 입력하세요
SELECT
    BOOK_ID,
    a.AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS b
INNER JOIN AUTHOR AS a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE CATEGORY = "경제"
ORDER BY PUBLISHED_DATE