-- 코드를 입력하세요
SELECT 
    DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
INNER JOIN CAR_RENTAL_COMPANY_CAR AS c
ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = "세단" AND MONTH(h.START_DATE) = 10
ORDER BY h.CAR_ID DESC
