-- 코드를 입력하세요
SELECT
    r.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW AS r
INNER JOIN (
    SELECT
        REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE "서울%"
) AS i
ON r.REST_ID = i.REST_ID
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC 